// Catálogo de marcas comercializadas en Chile. Fuente única de verdad,
// consumida por el form de /admin (lib/admin/vehicleOptions.ts) y por el
// schema de Sanity (sanity/schemaTypes/vehicle.ts) para mantener ambos
// dropdowns sincronizados.
export const VEHICLE_BRANDS = [
  'ALFA ROMEO',
  'AUDI',
  'BAIC',
  'BMW',
  'BYD',
  'CHANGAN',
  'CHERY',
  'CHEVROLET',
  'CHRYSLER',
  'CITROËN',
  'DFSK',
  'DODGE',
  'DS AUTOMOBILES',
  'FIAT',
  'FORD',
  'FOTON',
  'GEELY',
  'GREAT WALL (GWM)',
  'HAVAL',
  'HONDA',
  'HYUNDAI',
  'ISUZU',
  'JAC',
  'JAGUAR',
  'JEEP',
  'JMC',
  'KIA',
  'LAND ROVER',
  'LEXUS',
  'MAZDA',
  'MAXUS',
  'MERCEDES-BENZ',
  'MG',
  'MINI',
  'MITSUBISHI',
  'NISSAN',
  'OPEL',
  'PEUGEOT',
  'PORSCHE',
  'RAM',
  'RENAULT',
  'SKODA',
  'SSANGYONG',
  'SUBARU',
  'SUZUKI',
  'TOYOTA',
  'VOLKSWAGEN',
  'VOLVO',
] as const

// Valor especial para marcas no listadas. Se muestra siempre al final del
// dropdown, fuera del orden alfabético, y habilita un input de texto libre.
export const OTHER_BRAND_OPTION = 'Otra'
