import { Vehicle } from './types'
import { estimateMonthlyPayment } from './calculations'

// Mock vehicle data for development
export const mockVehicles: Vehicle[] = [
    {
        id: '1',
        slug: 'toyota-4runner-2020',
        brand: 'Toyota',
        model: '4Runner SR5 4x4',
        year: 2020,
        price: 28990000,
        monthlyPayment: estimateMonthlyPayment(28990000),
        km: 45000,
        transmission: 'Automático',
        fuelType: 'Gasolina',
        image: '/images/vehicles/toyota-4runner-2020.jpg',
        images: [
            '/images/vehicles/toyota-4runner-2020.jpg',
            '/images/vehicles/toyota-4runner-2020-2.jpg',
            '/images/vehicles/toyota-4runner-2020-3.jpg',
            '/images/vehicles/toyota-4runner-2020-4.jpg',
        ],
        isNew: true,
        specs: {
            engine: '4.0L V6',
            power: '270 HP',
            torque: '381 Nm',
            drivetrain: '4x4 Part-Time',
            seating: 7,
            color: 'Blanco Perla',
            doors: 4,
        },
        features: [
            'Control de Tracción',
            'Cámara de Retroceso',
            'Bluetooth',
            'Aire Acondicionado Dual',
            'Asientos de Cuero',
            'Sistema de Navegación',
        ],
    },
    {
        id: '2',
        slug: 'jeep-wrangler-2019',
        brand: 'Jeep',
        model: 'Wrangler Unlimited Sahara',
        year: 2019,
        price: 32990000,
        monthlyPayment: estimateMonthlyPayment(32990000),
        km: 38000,
        transmission: 'Automático',
        fuelType: 'Gasolina',
        image: '/images/vehicles/jeep-wrangler-2019.jpg',
        images: [
            '/images/vehicles/jeep-wrangler-2019.jpg',
            '/images/vehicles/jeep-wrangler-2019-2.jpg',
            '/images/vehicles/jeep-wrangler-2019-3.jpg',
        ],
        isNew: true,
        specs: {
            engine: '3.6L V6',
            power: '285 HP',
            torque: '347 Nm',
            drivetrain: '4x4 Full-Time',
            seating: 5,
            color: 'Negro',
            doors: 4,
        },
        features: [
            'Techo Removible',
            'Control de Descenso',
            'Sistema Uconnect',
            'Faros LED',
            'Ganchos de Remolque',
        ],
    },
    {
        id: '3',
        slug: 'ford-ranger-2021',
        brand: 'Ford',
        model: 'Ranger XLT 4x4',
        year: 2021,
        price: 24990000,
        monthlyPayment: estimateMonthlyPayment(24990000),
        km: 32000,
        transmission: 'Automático',
        fuelType: 'Diésel',
        image: '/images/vehicles/ford-ranger-2021.jpg',
        images: [
            '/images/vehicles/ford-ranger-2021.jpg',
            '/images/vehicles/ford-ranger-2021-2.jpg',
        ],
        isNew: false,
        specs: {
            engine: '2.0L Turbo Diesel',
            power: '213 HP',
            torque: '500 Nm',
            drivetrain: '4x4 Selectable',
            seating: 5,
            color: 'Gris Metálico',
            doors: 4,
        },
        features: [
            'Caja de Carga',
            'Control de Crucero',
            'SYNC 3',
            'Sensores de Estacionamiento',
        ],
    },
    {
        id: '4',
        slug: 'chevrolet-colorado-2020',
        brand: 'Chevrolet',
        model: 'Colorado High Country',
        year: 2020,
        price: 26990000,
        monthlyPayment: estimateMonthlyPayment(26990000),
        km: 41000,
        transmission: 'Automático',
        fuelType: 'Diésel',
        image: '/images/vehicles/chevrolet-colorado-2020.jpg',
        images: [
            '/images/vehicles/chevrolet-colorado-2020.jpg',
            '/images/vehicles/chevrolet-colorado-2020-2.jpg',
            '/images/vehicles/chevrolet-colorado-2020-3.jpg',
        ],
        isNew: false,
        specs: {
            engine: '2.8L Turbo Diesel',
            power: '200 HP',
            torque: '500 Nm',
            drivetrain: '4x4',
            seating: 5,
            color: 'Azul Oscuro',
            doors: 4,
        },
        features: [
            'MyLink',
            'Cámara 360°',
            'Asientos de Cuero',
            'Barra Antivuelco',
        ],
    },
    {
        id: '5',
        slug: 'nissan-frontier-2021',
        brand: 'Nissan',
        model: 'Frontier PRO-4X',
        year: 2021,
        price: 27990000,
        monthlyPayment: estimateMonthlyPayment(27990000),
        km: 28000,
        transmission: 'Automático',
        fuelType: 'Diésel',
        image: '/images/vehicles/nissan-frontier-2021.jpg',
        images: [
            '/images/vehicles/nissan-frontier-2021.jpg',
        ],
        isNew: true,
        specs: {
            engine: '2.3L Turbo Diesel',
            power: '190 HP',
            torque: '450 Nm',
            drivetrain: '4x4',
            seating: 5,
            color: 'Rojo',
            doors: 4,
        },
        features: [
            'Sistema PRO-4X',
            'Suspensión Bilstein',
            'NissanConnect',
            'Diferencial Trasero Bloqueado',
        ],
    },
    {
        id: '6',
        slug: 'mitsubishi-l200-2019',
        brand: 'Mitsubishi',
        model: 'L200 Triton Sport',
        year: 2019,
        price: 21990000,
        monthlyPayment: estimateMonthlyPayment(21990000),
        km: 52000,
        transmission: 'Manual',
        fuelType: 'Diésel',
        image: '/images/vehicles/mitsubishi-l200-2019.jpg',
        images: [
            '/images/vehicles/mitsubishi-l200-2019.jpg',
            '/images/vehicles/mitsubishi-l200-2019-2.jpg',
        ],
        isNew: false,
        specs: {
            engine: '2.4L Turbo Diesel',
            power: '181 HP',
            torque: '430 Nm',
            drivetrain: '4x4',
            seating: 5,
            color: 'Blanco',
            doors: 4,
        },
        features: [
            'Super Select 4WD',
            'Control de Estabilidad',
            'Bluetooth',
        ],
    },
]

// Filter options based on available vehicles
export const brandOptions = Array.from(
    new Set(mockVehicles.map((v) => v.brand))
).map((brand) => ({
    id: brand.toLowerCase(),
    name: brand,
    count: mockVehicles.filter((v) => v.brand === brand).length,
}))

export const transmissionOptions = [
    { id: 'automatico', name: 'Automático', count: mockVehicles.filter((v) => v.transmission === 'Automático').length },
    { id: 'manual', name: 'Manual', count: mockVehicles.filter((v) => v.transmission === 'Manual').length },
]

export const fuelTypeOptions = [
    { id: 'gasolina', name: 'Gasolina', count: mockVehicles.filter((v) => v.fuelType === 'Gasolina').length },
    { id: 'diesel', name: 'Diésel', count: mockVehicles.filter((v) => v.fuelType === 'Diésel').length },
    { id: 'hibrido', name: 'Híbrido', count: mockVehicles.filter((v) => v.fuelType === 'Híbrido').length },
    { id: 'electrico', name: 'Eléctrico', count: mockVehicles.filter((v) => v.fuelType === 'Eléctrico').length },
].filter((option) => option.count > 0)
